name: Publish Worker Docker Image

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'worker/**'
      - 'VERSION.txt'
  release:
    types: [ created ]

env:
  IMAGE_NAME: librarrarian-worker

jobs:
  build-and-push-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ forgejo.runner.context.forgejo.actions_url }}
          username: ${{ forgejo.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ forgejo.runner.context.forgejo.actions_url }}/${{ forgejo.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./worker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
